In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('Pokemon.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Pokemon.csv'

# Reading Data in Pandas

In [ ]:
## Rading Headers
print(df.columns)

##Reading Each Column
# print(df["Name"][0:5])

##Read Each Row
# print(df.iloc[0:4])
# for index,rows in df.iterrows():
#     print(index,rows["Name"])

## Read a specific location (R,C)
# print(df.iloc[2,1])
print(df.loc[df['Type 1'] == "Grass"])

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='str')
       #                   Name Type 1    Type 2  Total   HP  Attack  Defense  \
0      1              Bulbasaur  Grass    Poison    318   45      49       49
1      2                Ivysaur  Grass    Poison    405   60      62       63
2      3               Venusaur  Grass    Poison    525   80      82       83
3      3  VenusaurMega Venusaur  Grass    Poison    625   80     100      123
48    43                 Oddish  Grass    Poison    320   45      50       55
..   ...                    ...    ...       ...    ...  ...     ...      ...
718  650                Chespin  Grass       NaN    313   56      61       65
719  651              Quilladin  Grass       NaN    405   61      78       95
720  652             Chesnaught  Grass  Fighting    530   88     107      122
740  672                 Skiddo  Grass       NaN    350   66      65       48
741  673                 Gogoat  Grass       NaN    531  123     100       62

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
48        75       65     30           1      False
..       ...      ...    ...         ...        ...
718       48       45     38           6      False
719       56       58     57           6      False
720       74       75     64           6      False
740       62       57     52           6      False
741       97       81     68           6      False

[70 rows x 13 columns]

# Sorting and Describing

In [ ]:
df.sort_values(['Type 1', 'HP'], ascending=[True,False])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,295,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,340,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,200,20,15,20,10,55,80,3,False

In [28]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Total
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375,435.10250
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129,119.96304
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000,180.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000,330.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000,450.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000,515.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000,780.00000

# Transform Data

In [ ]:
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [27]:
# df["Total"] = df["HP"] + df["Attack"] + df["Defense"] + df["Sp. Atk"] + df["Sp. Def"] + df["Speed"]
# df = df.drop(columns=["Total"])

df['Total'] = df.iloc[:,4:10].sum(axis=1) #axis 1 = row wise, axis 0 = column wise

df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309