In [28]:
import pandas as pd

In [29]:
df = pd.read_csv('Pokemon.csv')

# Reading Data in Pandas

In [30]:
## Rading Headers
print(df.columns)

##Reading Each Column
# print(df["Name"][0:5])

##Read Each Row
# print(df.iloc[0:4])
# for index,rows in df.iterrows():
#     print(index,rows["Name"])

## Read a specific location (R,C)
# print(df.iloc[2,1])
print(df.loc[df['Type 1'] == "Grass"])

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='str')
       #                   Name Type 1    Type 2  Total   HP  Attack  Defense  \
0      1              Bulbasaur  Grass    Poison    318   45      49       49
1      2                Ivysaur  Grass    Poison    405   60      62       63
2      3               Venusaur  Grass    Poison    525   80      82       83
3      3  VenusaurMega Venusaur  Grass    Poison    625   80     100      123
48    43                 Oddish  Grass    Poison    320   45      50       55
..   ...                    ...    ...       ...    ...  ...     ...      ...
718  650                Chespin  Grass       NaN    313   56      61       65
719  651              Quilladin  Grass       NaN    405   61      78       95
720  652             Chesnaught  Grass  Fighting    530   88     107      122
740  672                 Skiddo  Grass       NaN    350   66      65       48
741  673                 Gogoat  Grass       NaN    531  123     100       62

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
48        75       65     30           1      False
..       ...      ...    ...         ...        ...
718       48       45     38           6      False
719       56       58     57           6      False
720       74       75     64           6      False
740       62       57     52           6      False
741       97       81     68           6      False

[70 rows x 13 columns]

# Sorting and Describing

In [31]:
df.sort_values(['Type 1', 'HP'], ascending=[True,False])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,295,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,340,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,200,20,15,20,10,55,80,3,False

In [32]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

# Transform Data

In [33]:
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [34]:
# df["Total"] = df["HP"] + df["Attack"] + df["Defense"] + df["Sp. Atk"] + df["Sp. Def"] + df["Speed"]
# df = df.drop(columns=["Total"])

df['Total'] = df.iloc[:,4:10].sum(axis=1) #axis 1 = row wise, axis 0 = column wise

df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,591,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,750,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,970,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,1170,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,553,39,52,43,60,50,65,1,False

# Saving Data in CSV

In [35]:
df.to_csv('modified.csv',index=False) #index = False means don't write row numbers

# Filtering Data

In [36]:
df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,970,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,1170,80,100,123,122,120,80,1,False
50,45,Vileplume,Grass,Poison,930,75,80,85,110,90,50,1,False
77,71,Victreebel,Grass,Poison,910,80,105,65,100,70,70,1,False
652,591,Amoonguss,Grass,Poison,898,114,85,70,85,80,30,5,False

In [37]:
import re

df.loc[(df['Type 1'].str.contains('Fire|Grass', regex=True))]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,591,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,750,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,970,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,1170,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,553,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,666,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,908,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,648,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,994,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,1130,80,110,120,130,90,70,6,True

In [38]:
df.loc[(df['Name']).str.contains('^pi[a-z]*',flags=re.I,regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,446,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,627,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,857,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,1037,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,550,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,915,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,1095,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,350,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,565,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,850,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,588,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,781,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,485,50,55,50,36,30,43,5,False

# Conditional Changes

In [39]:
df.loc[df['Type 1'] == 'Flame','Type 1'] = 'Fire'
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,591,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,750,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,970,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,1170,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,553,39,52,43,60,50,65,1,False